"""Initial migration.

Revision ID: 3dd4e01c9d33
Revises: 
Create Date: 2020-04-23 23:42:50.943269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd4e01c9d33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mhs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=10), nullable=True),
    sa.Column('nama', sa.String(length=25), nullable=True),
    sa.Column('kelas', sa.String(length=10), nullable=True),
    sa.Column('alamat', sa.String(length=52), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nim')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mhs')
    # ### end Alembic commands ###
